// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzzbnnivmbqtiprepxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6emJubml2bWJxdGlwcmVweGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDE5NzEsImV4cCI6MjA3NzgxNzk3MX0.gFjLz6HRB4_fjStcbaHfHCH8sqq0Ahb8lSJ9Q1Q_uRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});